from tkinter import *
var = Tk()

name = Label(var, text = "name")
password = Label(var, text = "password")
entry1 = Entry(var)
entry2 = Entry(var)
name.grid(row=0, sticky = E)
password.grid(row=1, sticky = E)
entry1.grid(row=0, column=1)
entry2.grid(row=1, column=1)
c = Checkbutton(var, text = "keep me logged in")
c.grid(row=2, columnspan=2)
# top_frame = Frame(var)
# top_frame.pack()
# bottom_frame = Frame(var)
# bottom_frame.pack(side = BOTTOM)
button_1 = Button(var, text = "Login", fg = "yellow", bg = "black")
button_2 = Button(var, text = "Reset")
button_1.grid(row=3, column=0)
button_2.grid(row=3, column=1)
var.mainloop() 